// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A wellness recommendation AI agent.
 *
 * - wellnessRecommendation - A function that handles the wellness recommendation process.
 * - WellnessRecommendationInput - The input type for the wellnessRecommendation function.
 * - WellnessRecommendationOutput - The return type for the wellnessRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const WellnessRecommendationInputSchema = z.object({
  healthDescription: z
    .string()
    .describe('A description of your current health and lifestyle.'),
});
export type WellnessRecommendationInput = z.infer<typeof WellnessRecommendationInputSchema>;

const WellnessRecommendationOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      service: z.string().describe('The name of the recommended service.'),
      description: z.string().describe('A description of the service and why it is recommended.'),
    })
  ).describe('A list of wellness recommendations based on the user input.'),
});
export type WellnessRecommendationOutput = z.infer<typeof WellnessRecommendationOutputSchema>;

export async function wellnessRecommendation(input: WellnessRecommendationInput): Promise<WellnessRecommendationOutput> {
  return wellnessRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'wellnessRecommendationPrompt',
  input: {schema: WellnessRecommendationInputSchema},
  output: {schema: WellnessRecommendationOutputSchema},
  prompt: `You are a wellness expert specializing in providing personalized wellness recommendations.

You will use the following information to provide recommendations for services such as yoga, ayurvedic treatment, and physiotherapy.

Health and Lifestyle Description: {{{healthDescription}}}

Based on the user's description, provide a list of services that would be beneficial, and a description of why each service is recommended. Focus on yoga, ayurvedic treatment, and physiotherapy.

Ensure the output is in the correct JSON format.`,
});

const wellnessRecommendationFlow = ai.defineFlow(
  {
    name: 'wellnessRecommendationFlow',
    inputSchema: WellnessRecommendationInputSchema,
    outputSchema: WellnessRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
