import RecommendationForm from '@/components/forms/RecommendationForm';
import PageHeader from '@/components/shared/PageHeader';
import { Wand2 } from 'lucide-react';

export default function RecommendationsPage() {
  return (
    <div className="space-y-12">
      <PageHeader
        title="Personalized Wellness Recommendations"
        subtitle="Answer a few questions about your health and lifestyle, and our AI-powered tool will suggest services tailored to your needs. This is not a substitute for professional medical advice."
        Icon={Wand2}
      />
      <RecommendationForm />
      <section className="mt-12 p-6 bg-primary/10 rounded-lg">
        <h3 className="text-2xl font-headline text-primary mb-3">Important Disclaimer</h3>
        <p className="text-foreground/80 leading-relaxed">
          The recommendations provided by this tool are generated by an AI model and are for informational purposes only. They do not constitute medical advice. Always consult with a qualified healthcare professional or one of our practitioners before making any decisions about your health or treatment. Our team is here to provide expert, personalized guidance.
        </p>
      </section>
    </div>
  );
}
